---
title: "Antibody Preprocessing Pipeline"
author: "CBT & Ritchie Lab"
date: today
format: dashboard
# server: shiny
knitr:
    opts_knit:
        root.dir: '../'
---

```{r}
# Install package
library(tidyverse)
library(vroom)
library(data.table)
library(ggplot2)
library(ggiraph)
library(plotly)
library(formattable)
library(DT)
library(bsicons)
library(bslib)
library(scales)
# library(shiny)
```

# Aligned reads

```{r}
#| label: ingest-aligned-reads-data
#| include: false

# Get list of files
files <- list.files(
    path = "./results/2_aligned_reads/stats",
    pattern = "\\.tsv$",
    full.names = TRUE
)

# Read in files
data_list <- lapply(files, fread, na.strings = c("N/A"))
# Add in barcode from file name as id col
names(data_list) <- str_replace(basename(files), "_alignment_stats.tsv", "")

# Combine datasets together and rename columns
combined_aligned_stats <- rbindlist(data_list, idcol = "barcode", fill = TRUE)
combined_aligned_stats <- rename(combined_aligned_stats,
    "QC_pass" = V1, "QC_fail" = V2, "category" = V3
)
```

``` {r}
#| label: ingest-sample-sheet-data
#| include: false

# Read in sample sheet information
sample_sheet <- read_csv("./data/reference_files/sample_sheet.csv")
sample_sheet <- sample_sheet %>% select(!report_group)
```

```{r}
#| label: parse-aligned-data
#| include: false

# Rename and extract required rows
rows_required <- list("total", "mapped", "mapped %", "primary", "secondary", "supplementary")
combined_aligned_stats <- combined_aligned_stats %>%
    mutate(category = ifelse(category == "total (QC-passed reads + QC-failed reads)",
        "total", category
    )) %>%
    select(-QC_fail) %>%
    mutate(QC_pass = ifelse(str_detect(QC_pass, "%"),
        as.numeric(str_replace(QC_pass, "%", "")),
        as.numeric(QC_pass)
    )) %>%
    filter(category %in% rows_required)
```

```{r}
#| label: data-aligned-wide
#| include: false

# Pivot table
combined_aligned_stats_wide <- combined_aligned_stats %>%
    pivot_wider(
        id_cols = barcode,
        names_from = category,
        values_from = QC_pass
    )

# Join sample sheet information to aligned stats
combined_aligned_stats_wide <- sample_sheet %>%
    left_join(combined_aligned_stats_wide, by = join_by(barcode)) %>%
    relocate(sample_name) %>%
    rename(mapped_perc = "mapped %") %>%
    mutate(mapped_perc = percent(mapped_perc / 100,
        accuracy = 1
    ))
```

```{r}
#| label: ingest-read-length-data
#| include: false

# Get list of files
files <- list.files(
    path = "./results/2_aligned_reads/read_lengths",
    pattern = "\\.tsv$",
    full.names = TRUE
)

# Read in files
data_list <- lapply(files, fread, na.strings = c("N/A"))
# Add in barcode from file name as id col
names(data_list) <- str_replace(basename(files), "_read_lengths.tsv", "")

# Combine datasets together and rename columns
read_lengths_table <- rbindlist(data_list, idcol = "barcode", fill = TRUE)
read_lengths_table <- rename(read_lengths_table,
    "read_length" = V1
)
```

## Row {height=150px}
```{r}
#| label: aligned-reads-value-boxes

# Get total samples number
samples <- combined_aligned_stats_wide %>%
    distinct(sample_name) %>%
    summarise(n = n()) %>%
    as.numeric()

# Get total barcodes number
barcodes <- combined_aligned_stats_wide %>%
    distinct(barcode) %>%
    summarise(n = n()) %>%
    as.numeric()

# Get total reads number
total_reads <- sum(combined_aligned_stats_wide$total)

# Set value box background colour
bg = "#B4ECE7"

# Create value boxes
vbs <- list(
    value_box(
        title = "Total samples",
        value = samples,
        showcase = bs_icon("flask"),
        theme = value_box_theme(bg = bg)
    ),
    value_box(
        title = "Total barcodes",
        value = barcodes,
        showcase = bs_icon("justify"),
        theme = value_box_theme(bg = bg)
    ),
    value_box(
        title = "Total reads",
        value = total_reads,
        showcase = bs_icon("body-text"),
        theme = value_box_theme(bg = bg)
    )
)

# Display value boxes
layout_column_wrap(
    width = 1/3,
    !!!vbs
)
```

## Row {.tabset}
```{r}
#| label: aligned-reads-table
#| title: "Sample alignment results and counts"

datatable(combined_aligned_stats_wide,
    filter = "top",
    rownames = FALSE,
    colnames = c(
        "Sample" = "sample_name",
        "Barcode" = "barcode",
        "Species" = "species",
        "Total reads" = "total",
        "Primary read" = "primary",
        "Secondary reads" = "secondary",
        "Supplementary reads" = "supplementary",
        "Mapped reads" = "mapped",
        "Mapped reads %" = "mapped_perc"
    ),
    options = list(
        autoWidth = TRUE,
        initComplete = JS(
            "function(settings, json) {",
            "$(this.api().table().container()).css({'font-size': '12px'});",
            "}"
        )
    )
)
```

```{r}
#| label: plot-read-length-histogram
#| title: Read length distribution

# Create histogram of read lengths
fig1 <- ggplot(
    data = read_lengths_table,
    aes(
        x = read_length, fill = barcode,
        text = paste0(
            "Count: ", after_stat(count),
            "<br>", fill
        )
    ),
) +
    geom_histogram(alpha = 0.7, boundary = 0, binwidth = 100) +
    scale_x_continuous(breaks = seq(0, max(read_lengths_table$read_length), 1000)) +
    labs(x = "Read length", y = "Number of reads") +
    guides(fill = guide_legend(title = "Barcode")) +
    theme_classic() +
    theme(panel.grid.major.y = element_line(color = "gray90", linewidth = 0.5))

# Output interactive plot
ggplotly(fig1, tooltip = "text") %>%
    # Download plot in svg format and provide default plot name
    config(
        toImageButtonOptions = list(
            format = "svg",
            filename = "read_length_distribution"
        )
    ) %>% 
    # Set plot to auto size
    layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

```{r}
#| label: plot-read-length-violin-plot
#| title: Read length distribution (comparison)

# Create violin plot of read lengths
fig2 <- read_lengths_table %>%
    plot_ly(
        x = ~barcode,
        y = ~log(read_length),
        split = ~barcode,
        meanline = list(visible = TRUE),
        type = "violin"
    )

# Output plot
fig2 %>%
    # Rename axes
    layout(
        xaxis = list(
            title = "Barcode"
        ),
        yaxis = list(
            title = "Log read length",
            zeroline = F
        )
    ) %>%
    # Download plot in svg format and provide default plot name
    config(
        toImageButtonOptions = list(
            format = "svg",
            filename = "read_length_distribution_comp"
        )
    )
```

# Extracted reads

```{r}
#| label: ingest-extracted-reads-data
#| include: false

# Get list of files
files_extracted_reads <- list.files(
    path = "./results/3_extracted_reads/best/counts",
    pattern = "\\.csv$",
    full.names = TRUE
)

# Read in files
data_list_extracted_reads <- lapply(files_extracted_reads, fread, na.strings = c("N/A"))
# Add in barcode from file name as id col
names(data_list_extracted_reads) <- str_replace(basename(files_extracted_reads), "_count.csv", "")

# Combine datasets together and rename columns
extracted_reads_best <- rbindlist(data_list_extracted_reads, 
idcol = "barcode", fill = TRUE)
extracted_reads_best <- rename(extracted_reads_best, "sequence" = value)

# Divide total reads by 2 (as duplicated when using reverse complement in matchbox)
extracted_reads_best <- extracted_reads_best %>%
    mutate(count = ifelse(sequence == "total reads", count / 2, count))

# Join sample sheet information to aligned stats
extracted_reads_best <- sample_sheet %>%
left_join(extracted_reads_best, by = join_by(barcode)) %>% 
relocate(sample_name)
```

## Row {height=150px}
```{r}
#| label: extracted-reads-value-boxes

# Get total reads
total_reads <- extracted_reads_best %>%
    filter(sequence == "total reads") %>%
    summarise(sum(count))

# # Get total rotated reads
# rotated_reads <- extracted_reads_best %>%
#     filter(sequence == "rotated") %>%
#     summarise(sum(count))

# Get total heavy chains
heavy_reads <- extracted_reads_best %>%
    filter(sequence == "heavy") %>%
    summarise(sum(count))

# Get total heavy chains
heavy_lambda_reads <- extracted_reads_best %>%
    filter(sequence == "heavy + lambda") %>%
    summarise(sum(count))

# Get total heavy chains
heavy_kappa_reads <- extracted_reads_best %>%
    filter(sequence == "heavy + kappa") %>%
    summarise(sum(count))

# Sum total light chain + heavy chains found
heavy_light_reads <- heavy_lambda_reads + heavy_kappa_reads

# Set value box background colour
bg <- "#B4ECE7"

# Create value boxes
vbs2 <- list(
    value_box(
        title = "Total reads",
        value = total_reads,
        showcase = bs_icon("body-text"),
        theme = value_box_theme(bg = bg)
    ),
    value_box(
        title = "Total heavy chains",
        value = heavy_reads,
        showcase = bs_icon("h-square"),
        theme = value_box_theme(bg = bg)
    ),
    # value_box(
    #     title = "Total heavy + lambda chains",
    #     value = heavy_lambda_reads,
    #     showcase = bs_icon("plus-circle"),
    #     theme = value_box_theme(bg = bg)
    # ),
    # value_box(
    #     title = "Total heavy + kappa chains",
    #     value = heavy_kappa_reads,
    #     showcase = bs_icon("plus-square"),
    #     theme = value_box_theme(bg = bg)
    # )
    value_box(
        title = "Total heavy + light chains",
        value = heavy_light_reads,
        showcase = bs_icon("segmented-nav"),
        theme = value_box_theme(bg = bg)
    )
)

# Display value boxes
layout_column_wrap(
    width = 1 / 3,
    !!!vbs2
)
```

## Row {.tabset}
```{r}
#| label: extracted-reads-table
#| title: "Extracted reads summary"

# Pivot extracted reads dataset to wide format
extracted_reads_best_wide <- extracted_reads_best %>%
    pivot_wider(names_from = sequence, values_from = count) %>% 
    rename("heavy_kappa" = "heavy + kappa",
    "heavy_lambda" = "heavy + lambda",
    "total_reads" = "total reads"
    ) %>%
    relocate('rotated', .after = species) %>% 
    relocate('total_reads', .after = species) %>% 
    mutate(recovery = percent((heavy_kappa + heavy_lambda)/total_reads, accuracy = 1))

# Output table
datatable(extracted_reads_best_wide,
    filter = "top",
    rownames = FALSE,
    colnames = c(
        "Sample" = "sample_name",
        "Barcode" = "barcode",
        "Species" = "species",
        "Total reads" = "total_reads",
        "Rotated reads" = "rotated",
        "Heavy chains" = "heavy",
        "Heavy + light (lambda) chains" = "heavy_lambda",
        "Heavy + light (kappa) chains" = "heavy_kappa",
        "Recovery %" = "recovery"
    ),
    options = list(
        autoWidth = TRUE,
        initComplete = JS(
            "function(settings, json) {",
            "$(this.api().table().container()).css({'font-size': '12px'});",
            "}"
        )
    )
)
```

``` {r}
#| label: calc-diff-prop

# Calculate correct proportions in relation to total sequences
extracted_reads_best <- extracted_reads_best %>%
    mutate(sequence = case_when(
        sequence %in% c("heavy + kappa", "heavy + lambda") ~ "heavy + light",
        .default = sequence
    )) %>%
    group_by(barcode, sequence) %>%
    summarise(count = sum(count)) %>%
    ungroup() %>%
    mutate(sequence = ordered(sequence, 
        levels = c("total reads", "rotated", "heavy", "heavy + light"))) %>%
    group_by(barcode) %>%
    arrange(barcode, desc(sequence)) %>%
    mutate(diff = count - lag(count, default = first(count))) %>%
    ungroup() %>%
    select(-count) %>%
    right_join(extracted_reads_best, by = join_by(barcode, sequence)) %>%
    mutate(diff = ifelse(is.na(diff), count, diff)) %>%
    mutate(sequence = factor(sequence, 
    levels = c("total reads", "rotated", "heavy", "heavy + kappa", "heavy + lambda"))) %>%
    arrange(barcode, sequence) %>%
    relocate(diff, .after = last_col())

# Create new data frame for proportions
extracted_reads_best_prop <- extracted_reads_best %>%
    group_by(barcode) %>%
    mutate(prop = diff / count[sequence == "total reads"]) %>%
    ungroup()
```

```{r}
#| label: plot-extracted-reads-seq-histogram
#| title: Extracted read sequences per barcode

# Plot sequence counts as fills on each barcode
fig3 <- extracted_reads_best %>%
    ggplot(
        aes(
        fill = sequence, 
        text = paste0(
            "Sequence: ", sequence,
            "<br>Count: ", diff
            )
        )
    ) + 

    geom_col(
        data = extracted_reads_best[(extracted_reads_best[, "sequence"] == "total reads"), ],
        aes(y = fct_reorder(barcode, count), x = count),
    ) + 

    geom_col(
        data = extracted_reads_best[(extracted_reads_best[, "sequence"] == "rotated"), ],
        aes(y = fct_reorder(barcode, count), x = count),
    ) +

    geom_col(
        data = extracted_reads_best[(extracted_reads_best[, "sequence"] == "heavy"), ],
        aes(y = fct_reorder(barcode, count), x = count)
    ) +
    
    geom_col(
        data = extracted_reads_best[(extracted_reads_best[, "sequence"] == "heavy + kappa" | extracted_reads_best[, "sequence"] == "heavy + lambda"), ],
        aes(y = fct_reorder(barcode, count), x = count)
    )

# Customise plot
fig3 <- fig3 + labs(x = "Number of sequences", y = "Barcode") +
    theme_classic() +
    scale_fill_manual(
        values = c(
            "total reads" = "#CAEEEC",
            "rotated" = "#E5CFC2",
            "heavy" = "#CBEDB1",
            "heavy + kappa" = "#F8BAC9",
            "heavy + lambda" = "#FFCBAE"
        ),
        # breaks = c("total reads", "rotated", "heavy", "heavy + kappa", "heavy + lambda"),
        # labels = c("Total reads", "Rotated reads", "Heavy chains", "Heavy + light (kappa) chains", "Heavy + light (lambda) chains"),
        name = "Sequence"
    )

# Output plot
ggplotly(fig3, tooltip = "text") %>%
    # Download plot in svg format and provide default plot name
    config(
        toImageButtonOptions = list(
            format = "svg",
            filename = "extracted_reads"
        )
    ) %>% 
    # Set plot to auto size
    layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

```{r}
#| label: plot-extracted-reads-seq-proportion
#| title: Proportion of extracted read sequences per barcode

# Plot proportion of sequences extracted through matchbox
fig4 <- extracted_reads_best_prop %>%
    ggplot(
        aes(
            y = fct_reorder(barcode, count),
            x = prop,
            fill = sequence,
            text = paste0(
                "Sequence: ", sequence,
                "<br>Proportion: ", round(prop, 2)
            )
        )
    ) +
    geom_col(position = "stack") +
    guides(fill = guide_legend(reverse = TRUE)) +
    scale_fill_manual(values = c(
        "total reads" = "#CAEEEC",
        "rotated" = "#E5CFC2",
        "heavy" = "#CBEDB1",
        "heavy + kappa" = "#F8BAC9",
        "heavy + lambda" = "#FFCBAE"
    )) +
    labs(x = "Proportion of sequences", y = "Barcode", fill = "Sequence") +
    theme_classic()

# Output plot
ggplotly(fig4, tooltip = "text") %>%
    # Download plot in svg format and provide default plot name
    config(
        toImageButtonOptions = list(
            format = "svg",
            filename = "extracted_reads_prop"
        )
    ) %>%
    # Set plot to auto size
    layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

# Annotated reads

```{r}
#| label: ingest-annotated-reads-data
#| include: false

# Get list of files
files_annot_reads <- list.files(
    path = "./results/4_annotated_reads/best",
    pattern = "\\.csv$",
    full.names = TRUE
)

# Read in files
data_list_annot_reads <- lapply(files_annot_reads, fread, na.strings = c("N/A"))
# Add in barcode from file name as id col
names(data_list_annot_reads) <- str_replace(basename(files_annot_reads), "_annot_(heavy|light).csv", "")

# Combine datasets together and rename columns
annot_reads_best <- rbindlist(data_list_annot_reads, 
idcol = "barcode", fill = TRUE) %>% 
select(barcode, productive)

# Join sample sheet information to annotated stats
annot_reads_best <- sample_sheet %>%
left_join(annot_reads_best, by = join_by(barcode)) %>% 
relocate(sample_name)
```

```{r}
#| label: data-productivity
#| include: false

# Get data on productive reads
productive_df <- annot_reads_best %>% 
group_by(barcode, productive) %>%
summarise(count = n()) %>% 
mutate(prop = count/sum(count)) %>%
filter(productive == TRUE)
```

## Row {height=5%}
::: {.card}
The read productivity is the proportion of reads that do not contain a stop
:::

## Row
```{r}
#| label: plot-read-productivity
#| title: Read productivity

# Get data on productive reads
productive_df <- annot_reads_best %>%
    group_by(barcode, productive) %>%
    summarise(count = n()) %>%
    mutate(prop = count / sum(count)) %>%
    filter(productive == TRUE)

# Plot proportion of productive reads
fig5 <- ggplot(
    data = productive_df,
    aes(
        x = prop,
        y = fct_rev(barcode),
        text = paste0(
            "Proportion: ", round(prop, 2),
            "<br>Count: ", count
        )
    )
) +
    geom_col(fill = "#E5CFC2") +
    theme_classic() +
    labs(y = "Barcode", x = "Proportion")

# Output plot
ggplotly(fig5, tooltip = "text") %>%
    # Download plot in svg format and provide default plot name
    config(
        toImageButtonOptions = list(
            format = "svg",
            filename = "read_productivity"
        )
    ) %>%
    # Set plot to auto size
    layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```
