%%metro title: AbPreP
%%metro style: nfcore

%% metro fold_threshold: 4
%%metro x_spacing: 121
%%metro diamond_style: symmetric

%% metro label_angle: 

%%metro line: main | Main pipeline | #BCE1B9
%%metro line: qc | QC | #D1DCF3 | dashed
%%metro legend: bl | canvas


%%metro file: samplesheet | CSV | Samplesheet
%%metro files: samples | FASTQ | Samples
%%metro file: matchbox_script | MB | Matchbox script
%%metro file: reference | FA | Reference genome
%%metro file: indexed_sam | SAM | Aligned\nsequences
%%metro file: qc_html | HTML | QC report
%%metro files: counts_csv | CSV | Counts\nmatrix
%%metro files: annotated_csv | CSV | Annotated\nsequences

%%metro off_track: indexed_sam, counts_csv, annotated_csv, matchbox_script

%%metro grid: inputs | 0,0
%%metro grid: alignment | 1,1
%%metro grid: extraction, qc | 1,0
%% metro grid: qc | 2,0


graph LR

    subgraph inputs [Inputs]
        %% nodes
		samplesheet[ ]
		samples[ ]
        input_branch[]
        
        %% edges
        samplesheet --> |main, qc| input_branch
        samples --> |main, qc| input_branch
        %% reference --> |qc| input_branch
    end

	
    subgraph extraction [Sequence extraction & annotation]
    	%% metro exit: bottom | qc
        
        %% nodes
        matchbox[Extract VH, VL\nmatchbox]
        errorcorr[Error correction]
        riot[Annotate sequences\nriot]
        counts[Create counts matrix]
        _extract_end_node
        after_counts[]
        matchbox_script[ ]
        
        matchbox_script --> |main| matchbox  
        
        %% edges
		matchbox -->|main| errorcorr
        errorcorr -->|main| riot
        riot -->|main| counts
        %% counts -->|main| after_counts
        
        matchbox -->|qc| _extract_end_node
        riot -->|qc| _extract_end_node
                
        counts -->|main| counts_csv
		riot -->|main| annotated_csv
    end
    

    subgraph alignment [Alignment]
        %% nodes
        minimap2[Align sequences\nminimap2]
        samtools[Alignment statistics\nsamtools]
        indexed_sam[ ]
        reference[ ]

		%% edges
        reference -->|qc| minimap2
        minimap2 -->|qc| samtools
        samtools -->|qc| indexed_sam
    end



    subgraph qc [QC reporting]
		%% metro entry: bottom | qc
        %% metro direction: RL
    	%% nodes
        qc_html[ ]
        qcreport[Create QC report]
        
        %% edges
        qcreport -->|qc| qc_html

    end


    subgraph outputs [Outputs]
    	%% nodes
		
        
        counts_csv[ ]
        annotated_csv[ ]
        
    end
       
        
%% Inter-section edges - inputs
input_branch -->|main| matchbox
input_branch -->|qc| minimap2


%% Inter-section edges - join into QC
samtools -->|qc| qcreport
_extract_end_node -->|qc| qcreport
