read_dir: "${projectDir}/data/reads"
sample_sheet: "/vast/projects/antibody_sequencing/preprocessing_pipeline/data/reference_files/sample_sheet.csv"
phagemid_ref: "/vast/projects/antibody_sequencing/preprocessing_pipeline/data/reference_files/fab_phagemid.fa"
matchbox_script: "/vast/projects/antibody_sequencing/preprocessing_pipeline/bin/matchbox_preprocessing_script.mb"
matchbox_parameters: "/vast/projects/antibody_sequencing/preprocessing_pipeline/data/reference_files/matchbox_parameters.csv"
output_dir: "results"
help: false
enable_conda: false
nanobody: false